[project]
name = "genie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "genie-tts>=2.0.2",
    "pydub>=0.25.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.5",
    "fastapi>=0.111.0",
    "uvicorn>=0.30.0",
]
